# Generated by Django 2.2.1 on 2019-05-12 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('sentby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentby', to=settings.AUTH_USER_MODEL)),
                ('sentto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
